short_name = "faton"
name = "Faton Engine"
status = "in development"
year = "2020"
website = "http://www.semyondyachenko.info"
development_platform = "win 64 (Microsoft Windows 10 Pro), Microsoft Visual Studio 2019"
